GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib3duZXIiLCJpYXQiOjE2ODc2NzMzMTMsImV4cCI6MTY4NzY3NjkxM30.FDvALUPEf7976vAm9woaLTEu9Q5r2tZKKbinY_MEP64
Content-Type: application/json


###


POST http://localhost:8080/login
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImlhdCI6MTY4NzY0NTAxMywiZXhwIjoxNjg3NjQ4NjEzfQ.vKUpKIHawmUs7EKwUhM73gNlLYJhuiDAlwsa579Jwso
Content-Type: application/json

{
    "username": "owner",
    "password": "owner9962@"
}

# at: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImlhdCI6MTY4NzY0NTAxMywiZXhwIjoxNjg3NjQ4NjEzfQ.vKUpKIHawmUs7EKwUhM73gNlLYJhuiDAlwsa579Jwso
# rt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImlhdCI6MTY4NzY0NTAxM30.-h5xOLP_NSyi-x1Ckh-A_jeNwna6ulEQYFu4TyzRjFA

#owner
# at: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib3duZXIiLCJpYXQiOjE2ODc2NDU3NjIsImV4cCI6MTY4NzY0OTM2Mn0.Di_uFKbO0zwNS6_0wLen2gcIoY9pb78QkrImTVvqOgM
# rt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib3duZXIiLCJpYXQiOjE2ODc2NDU3NjJ9.lWVh6pra8haqrQLRzjwJ7TlPbNmbMl_23FOWYn1g5M0
###


POST http://localhost:8080/login
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImlhdCI6MTY4NzY0NTAxMywiZXhwIjoxNjg3NjQ4NjEzfQ.vKUpKIHawmUs7EKwUhM73gNlLYJhuiDAlwsa579Jwso
Content-Type: application/json

{
    "username": "owner",
    "password": "owner9962@"
}


###


POST http://localhost:8080/login/rt
Content-Type: application/json

{
    "rt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib3duZXIiLCJpYXQiOjE2ODc4NjA3ODR9.nTpsU1ZxeDdFtY8pKYvYFBjCn2l_l1huRpc0035FQRU"
}


###


POST http://localhost:8080/register
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImlhdCI6MTY4NzY0NTAxMywiZXhwIjoxNjg3NjQ4NjEzfQ.vKUpKIHawmUs7EKwUhM73gNlLYJhuiDAlwsa579Jwso
Content-Type: application/json

{
    "username": "owner",
    "email": "o@o",
    "password": "owner9962@"
}


###


GET http://localhost:8080/post/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib3duZXIiLCJpYXQiOjE2ODc4MTcyNTAsImV4cCI6MTY4NzgyMDg1MH0.gD0-lS6t4LN_sW3iIfZJaxYraMx8QWlh94_KIS85ebw
Content-Type: application/json


###


POST http://localhost:8080/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib3duZXIiLCJpYXQiOjE2ODc4MzM0MDQsImV4cCI6MTY4NzgzNzAwNH0.EeqO5yUQT_pluK9HbbsrVVT_WLJ-X-cyxwBBX9cw0jI
Content-Type: application/json

{
    "like": true,
    "status": "add"
}


###


PUT http://localhost:8080/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib3duZXIiLCJpYXQiOjE2ODc4Mzc2NDYsImV4cCI6MTY4Nzg0MTI0Nn0.vddxrcFwAkl7e0fMiTr70ImPvnsaSJx1kV1o-MfnTUU
Content-Type: application/json

{
    "like": false,
    "status": "update"
}


###


DELETE  http://localhost:8080/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib3duZXIiLCJpYXQiOjE2ODc2ODEzOTYsImV4cCI6MTY4NzY4NDk5Nn0.Mn2Qh80lVjyttq-t4e4yDybZU3aQFEE63WNoi2ZM6bw
Content-Type: application/json

{
    "delete": true
}